In [2]:
import numpy as np
import pandas as pd

In [3]:
data={
    'Date':pd.date_range('2023-01-01',periods=20),
    'Product':['A','B','C','D']*5,
    'Region':['East','West','North','South','East','West','North','South','East','West','North','South','East','West','North','South','East','West','North','South'],
    'Sales':np.random.randint(100,1000,20),
    'Units':np.random.randint(10,100,20),
    'Rep':['Jhon','Mary','Bob','Alice','Jhon','Mary','Bob','Alice','Jhon','Mary','Bob','Alice','Jhon','Mary','Bob','Alice','Jhon','Mary','Bob','Alice']
}
df=pd.DataFrame(data)
df['Month']=df['Date'].dt.month_name()
df['Quarter']='Q'+df['Date'].dt.quarter.astype(str)

In [4]:
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    902     15   Jhon  January      Q1
1  2023-01-02       B   West    675     86   Mary  January      Q1
2  2023-01-03       C  North    455     24    Bob  January      Q1
3  2023-01-04       D  South    717     57  Alice  January      Q1
4  2023-01-05       A   East    843     51   Jhon  January      Q1
5  2023-01-06       B   West    313     41   Mary  January      Q1
6  2023-01-07       C  North    833     75    Bob  January      Q1
7  2023-01-08       D  South    187     55  Alice  January      Q1
8  2023-01-09       A   East    854     79   Jhon  January      Q1
9  2023-01-10       B   West    546     54   Mary  January      Q1
10 2023-01-11       C  North    103     33    Bob  January      Q1
11 2023-01-12       D  South    680     55  Alice  January      Q1
12 2023-01-13       A   East    483     78   Jhon  January      Q1
13 2023-01-14       B   West    229     12   Mary  January      Q1
14 2023-01-15       C  North    183     16    Bob  January      Q1
15 2023-01-16       D  South    807     13  Alice  January      Q1
16 2023-01-17       A   East    437     14   Jhon  January      Q1
17 2023-01-18       B   West    639     63   Mary  January      Q1
18 2023-01-19       C  North    621     88    Bob  January      Q1
19 2023-01-20       D  South    944     80  Alice  January      Q1

In [5]:
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0