In [7]:
import numpy as np
import pandas as pd

In [10]:
data={
    'Date':pd.date_range('2023-01-01',periods=20),
    'Product':['A','B','C','D']*5,
    'Region':['East','West','North','South','East','West','North','South','East','West','North','South','East','West','North','South','East','West','North','South'],
    'Sales':np.random.randint(100,1000,20),
    'Units':np.random.randint(10,100,20),
    'Rep':['Jhon','Mary','Bob','Alice','Jhon','Mary','Bob','Alice','Jhon','Mary','Bob','Alice','Jhon','Mary','Bob','Alice','Jhon','Mary','Bob','Alice']
}
df=pd.DataFrame(data)
df['Month']=df['Date'].dt.month_name()
df['Quarter']='Q'+df['Date'].dt.quarter.astype(str)

In [11]:
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    321     32   Jhon  January      Q1
1  2023-01-02       B   West    996     27   Mary  January      Q1
2  2023-01-03       C  North    687     50    Bob  January      Q1
3  2023-01-04       D  South    246     26  Alice  January      Q1
4  2023-01-05       A   East    337     53   Jhon  January      Q1
5  2023-01-06       B   West    783     99   Mary  January      Q1
6  2023-01-07       C  North    342     21    Bob  January      Q1
7  2023-01-08       D  South    757     49  Alice  January      Q1
8  2023-01-09       A   East    943     27   Jhon  January      Q1
9  2023-01-10       B   West    639     98   Mary  January      Q1
10 2023-01-11       C  North    660     42    Bob  January      Q1
11 2023-01-12       D  South    707     36  Alice  January      Q1
12 2023-01-13       A   East    545     90   Jhon  January      Q1
13 2023-01-14       B   West    950     66   Mary  January      Q1
14 2023-01-15       C  North    325     34    Bob  January      Q1
15 2023-01-16       D  South    528     58  Alice  January      Q1
16 2023-01-17       A   East    680     11   Jhon  January      Q1
17 2023-01-18       B   West    681     60   Mary  January      Q1
18 2023-01-19       C  North    664     36    Bob  January      Q1
19 2023-01-20       D  South    412     71  Alice  January      Q1

In [ ]:
#by default aggfunc='mean' and values must be numeric
pd.pivot_table(df,values="Sales",index="Region",columns="Product")

Product      A      B      C      D
Region
East     565.2    NaN    NaN    NaN
North      NaN    NaN  535.6    NaN
South      NaN    NaN    NaN  530.0
West       NaN  809.8    NaN    NaN

In [13]:
pd.pivot_table(df,values="Sales",index="Region",columns="Product",aggfunc='median')

Product      A      B      C      D
Region
East     545.0    NaN    NaN    NaN
North      NaN    NaN  660.0    NaN
South      NaN    NaN    NaN  528.0
West       NaN  783.0    NaN    NaN

In [14]:
pd.pivot_table(df,values=["Sales","Units"],index="Region",columns="Product")

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     565.2    NaN    NaN    NaN  42.6   NaN   NaN   NaN
North      NaN    NaN  535.6    NaN   NaN   NaN  36.6   NaN
South      NaN    NaN    NaN  530.0   NaN   NaN   NaN  48.0
West       NaN  809.8    NaN    NaN   NaN  70.0   NaN   NaN