In [2]:
import numpy as np
import pandas as pd

In [4]:
data_list1=[
    ['John',28,'New York',65000],
    ['Anna',34,'Paris',70000],
    ['Peter',29,'Berlin',62000],
    ['Linda',42,'London',85000]
]
df2=pd.DataFrame(data_list1)
col=['Name','Age','City','Salary']
df2=pd.DataFrame(data_list1,columns=col)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
#Selection and Indexing
df2['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

In [6]:
df2['City']

0    New York
1       Paris
2      Berlin
3      London
Name: City, dtype: str

In [ ]:
#column selection
df2[['Name','City']]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London